# Generated by Django 2.2.4 on 2019-08-08 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_photo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
