# Generated by Django 2.2.4 on 2019-08-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190808_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.CharField(blank=True, max_length=10, verbose_name='키'),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.CharField(blank=True, max_length=10, verbose_name='몸무게'),
        ),
    ]
